/*
 * This file is generated by jOOQ.
 */
package io.ehdev.account.db.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "rule_grant", schema = "account_manager", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"rule_id", "user_id"})
}, indexes = {
    @Index(name = "grant_to_user", columnList = "user_id ASC"),
    @Index(name = "PRIMARY", unique = true, columnList = "grant_id ASC"),
    @Index(name = "rule_id", unique = true, columnList = "rule_id ASC, user_id ASC")
})
public class RuleGrant implements Serializable {

    private static final long serialVersionUID = -99572009;

    private Long grantId;
    private Long ruleId;
    private Long userId;

    public RuleGrant() {}

    public RuleGrant(RuleGrant value) {
        this.grantId = value.grantId;
        this.ruleId = value.ruleId;
        this.userId = value.userId;
    }

    public RuleGrant(
        Long grantId,
        Long ruleId,
        Long userId
    ) {
        this.grantId = grantId;
        this.ruleId = ruleId;
        this.userId = userId;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "grant_id", unique = true, nullable = false, precision = 19)
    public Long getGrantId() {
        return this.grantId;
    }

    public void setGrantId(Long grantId) {
        this.grantId = grantId;
    }

    @Column(name = "rule_id", nullable = false, precision = 19)
    @NotNull
    public Long getRuleId() {
        return this.ruleId;
    }

    public void setRuleId(Long ruleId) {
        this.ruleId = ruleId;
    }

    @Column(name = "user_id", nullable = false, precision = 19)
    @NotNull
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RuleGrant (");

        sb.append(grantId);
        sb.append(", ").append(ruleId);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
