/*
 * This file is generated by jOOQ.
 */
package io.ehdev.account.db.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "ss_UserConnection", schema = "account_manager", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"userId", "providerId", "providerUserId"}),
    @UniqueConstraint(columnNames = {"userId", "providerId", "rank"})
}, indexes = {
    @Index(name = "PRIMARY", unique = true, columnList = "userId ASC, providerId ASC, providerUserId ASC"),
    @Index(name = "UserConnectionRank", unique = true, columnList = "userId ASC, providerId ASC, rank ASC")
})
public class SsUserconnection implements Serializable {

    private static final long serialVersionUID = 180105747;

    private String  userid;
    private String  providerid;
    private String  provideruserid;
    private Integer rank;
    private String  displayname;
    private String  profileurl;
    private String  imageurl;
    private String  accesstoken;
    private String  secret;
    private String  refreshtoken;
    private Long    expiretime;

    public SsUserconnection() {}

    public SsUserconnection(SsUserconnection value) {
        this.userid = value.userid;
        this.providerid = value.providerid;
        this.provideruserid = value.provideruserid;
        this.rank = value.rank;
        this.displayname = value.displayname;
        this.profileurl = value.profileurl;
        this.imageurl = value.imageurl;
        this.accesstoken = value.accesstoken;
        this.secret = value.secret;
        this.refreshtoken = value.refreshtoken;
        this.expiretime = value.expiretime;
    }

    public SsUserconnection(
        String  userid,
        String  providerid,
        String  provideruserid,
        Integer rank,
        String  displayname,
        String  profileurl,
        String  imageurl,
        String  accesstoken,
        String  secret,
        String  refreshtoken,
        Long    expiretime
    ) {
        this.userid = userid;
        this.providerid = providerid;
        this.provideruserid = provideruserid;
        this.rank = rank;
        this.displayname = displayname;
        this.profileurl = profileurl;
        this.imageurl = imageurl;
        this.accesstoken = accesstoken;
        this.secret = secret;
        this.refreshtoken = refreshtoken;
        this.expiretime = expiretime;
    }

    @Column(name = "userId", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getUserid() {
        return this.userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    @Column(name = "providerId", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getProviderid() {
        return this.providerid;
    }

    public void setProviderid(String providerid) {
        this.providerid = providerid;
    }

    @Column(name = "providerUserId", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getProvideruserid() {
        return this.provideruserid;
    }

    public void setProvideruserid(String provideruserid) {
        this.provideruserid = provideruserid;
    }

    @Column(name = "rank", nullable = false, precision = 10)
    @NotNull
    public Integer getRank() {
        return this.rank;
    }

    public void setRank(Integer rank) {
        this.rank = rank;
    }

    @Column(name = "displayName", length = 255)
    @Size(max = 255)
    public String getDisplayname() {
        return this.displayname;
    }

    public void setDisplayname(String displayname) {
        this.displayname = displayname;
    }

    @Column(name = "profileUrl", length = 512)
    @Size(max = 512)
    public String getProfileurl() {
        return this.profileurl;
    }

    public void setProfileurl(String profileurl) {
        this.profileurl = profileurl;
    }

    @Column(name = "imageUrl", length = 512)
    @Size(max = 512)
    public String getImageurl() {
        return this.imageurl;
    }

    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    @Column(name = "accessToken", nullable = false, length = 512)
    @NotNull
    @Size(max = 512)
    public String getAccesstoken() {
        return this.accesstoken;
    }

    public void setAccesstoken(String accesstoken) {
        this.accesstoken = accesstoken;
    }

    @Column(name = "secret", length = 512)
    @Size(max = 512)
    public String getSecret() {
        return this.secret;
    }

    public void setSecret(String secret) {
        this.secret = secret;
    }

    @Column(name = "refreshToken", length = 512)
    @Size(max = 512)
    public String getRefreshtoken() {
        return this.refreshtoken;
    }

    public void setRefreshtoken(String refreshtoken) {
        this.refreshtoken = refreshtoken;
    }

    @Column(name = "expireTime", precision = 19)
    public Long getExpiretime() {
        return this.expiretime;
    }

    public void setExpiretime(Long expiretime) {
        this.expiretime = expiretime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SsUserconnection (");

        sb.append(userid);
        sb.append(", ").append(providerid);
        sb.append(", ").append(provideruserid);
        sb.append(", ").append(rank);
        sb.append(", ").append(displayname);
        sb.append(", ").append(profileurl);
        sb.append(", ").append(imageurl);
        sb.append(", ").append(accesstoken);
        sb.append(", ").append(secret);
        sb.append(", ").append(refreshtoken);
        sb.append(", ").append(expiretime);

        sb.append(")");
        return sb.toString();
    }
}
