/*
 * This file is generated by jOOQ.
 */
package io.ehdev.account.db.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "target", schema = "account_manager", indexes = {
    @Index(name = "PRIMARY", unique = true, columnList = "target_id ASC"),
    @Index(name = "target_name", unique = true, columnList = "target_name ASC")
})
public class Target implements Serializable {

    private static final long serialVersionUID = -312944583;

    private Long   targetId;
    private String targetName;

    public Target() {}

    public Target(Target value) {
        this.targetId = value.targetId;
        this.targetName = value.targetName;
    }

    public Target(
        Long   targetId,
        String targetName
    ) {
        this.targetId = targetId;
        this.targetName = targetName;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "target_id", unique = true, nullable = false, precision = 19)
    public Long getTargetId() {
        return this.targetId;
    }

    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    @Column(name = "target_name", unique = true, nullable = false, length = 128)
    @NotNull
    @Size(max = 128)
    public String getTargetName() {
        return this.targetName;
    }

    public void setTargetName(String targetName) {
        this.targetName = targetName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Target (");

        sb.append(targetId);
        sb.append(", ").append(targetName);

        sb.append(")");
        return sb.toString();
    }
}
