/*
 * This file is generated by jOOQ.
 */
package io.ehdev.account.db.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "target_access_rule", schema = "account_manager", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"target_id", "resource_name", "action_name"})
}, indexes = {
    @Index(name = "PRIMARY", unique = true, columnList = "rule_id ASC"),
    @Index(name = "target_id", unique = true, columnList = "target_id ASC, resource_name ASC, action_name ASC")
})
public class TargetAccessRule implements Serializable {

    private static final long serialVersionUID = -931216005;

    private Long   ruleId;
    private Long   targetId;
    private String resourceName;
    private String actionName;

    public TargetAccessRule() {}

    public TargetAccessRule(TargetAccessRule value) {
        this.ruleId = value.ruleId;
        this.targetId = value.targetId;
        this.resourceName = value.resourceName;
        this.actionName = value.actionName;
    }

    public TargetAccessRule(
        Long   ruleId,
        Long   targetId,
        String resourceName,
        String actionName
    ) {
        this.ruleId = ruleId;
        this.targetId = targetId;
        this.resourceName = resourceName;
        this.actionName = actionName;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "rule_id", unique = true, nullable = false, precision = 19)
    public Long getRuleId() {
        return this.ruleId;
    }

    public void setRuleId(Long ruleId) {
        this.ruleId = ruleId;
    }

    @Column(name = "target_id", nullable = false, precision = 19)
    @NotNull
    public Long getTargetId() {
        return this.targetId;
    }

    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    @Column(name = "resource_name", nullable = false, length = 128)
    @NotNull
    @Size(max = 128)
    public String getResourceName() {
        return this.resourceName;
    }

    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    @Column(name = "action_name", nullable = false, length = 128)
    @NotNull
    @Size(max = 128)
    public String getActionName() {
        return this.actionName;
    }

    public void setActionName(String actionName) {
        this.actionName = actionName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TargetAccessRule (");

        sb.append(ruleId);
        sb.append(", ").append(targetId);
        sb.append(", ").append(resourceName);
        sb.append(", ").append(actionName);

        sb.append(")");
        return sb.toString();
    }
}
