/*
 * This file is generated by jOOQ.
 */
package io.ehdev.account.db;


import io.ehdev.account.db.tables.FlywaySchemaHistoryTable;
import io.ehdev.account.db.tables.RuleGrantTable;
import io.ehdev.account.db.tables.SsUserconnectionTable;
import io.ehdev.account.db.tables.TargetAccessRuleTable;
import io.ehdev.account.db.tables.TargetTable;
import io.ehdev.account.db.tables.UserDetailsTable;
import io.ehdev.account.db.tables.UserTokensTable;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountManager extends SchemaImpl {

    private static final long serialVersionUID = -1073386005;

    /**
     * The reference instance of <code>account_manager</code>
     */
    public static final AccountManager ACCOUNT_MANAGER = new AccountManager();

    /**
     * The table <code>account_manager.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistoryTable FLYWAY_SCHEMA_HISTORY = io.ehdev.account.db.tables.FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>account_manager.rule_grant</code>.
     */
    public final RuleGrantTable RULE_GRANT = io.ehdev.account.db.tables.RuleGrantTable.RULE_GRANT;

    /**
     * The table <code>account_manager.ss_UserConnection</code>.
     */
    public final SsUserconnectionTable SS_USERCONNECTION = io.ehdev.account.db.tables.SsUserconnectionTable.SS_USERCONNECTION;

    /**
     * The table <code>account_manager.target</code>.
     */
    public final TargetTable TARGET = io.ehdev.account.db.tables.TargetTable.TARGET;

    /**
     * The table <code>account_manager.target_access_rule</code>.
     */
    public final TargetAccessRuleTable TARGET_ACCESS_RULE = io.ehdev.account.db.tables.TargetAccessRuleTable.TARGET_ACCESS_RULE;

    /**
     * The table <code>account_manager.user_details</code>.
     */
    public final UserDetailsTable USER_DETAILS = io.ehdev.account.db.tables.UserDetailsTable.USER_DETAILS;

    /**
     * The table <code>account_manager.user_tokens</code>.
     */
    public final UserTokensTable USER_TOKENS = io.ehdev.account.db.tables.UserTokensTable.USER_TOKENS;

    /**
     * No further instances allowed
     */
    private AccountManager() {
        super("account_manager", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY,
            RuleGrantTable.RULE_GRANT,
            SsUserconnectionTable.SS_USERCONNECTION,
            TargetTable.TARGET,
            TargetAccessRuleTable.TARGET_ACCESS_RULE,
            UserDetailsTable.USER_DETAILS,
            UserTokensTable.USER_TOKENS);
    }
}
