/*
 * This file is generated by jOOQ.
 */
package io.ehdev.account.db;


import io.ehdev.account.db.tables.FlywaySchemaHistoryTable;
import io.ehdev.account.db.tables.RuleGrantTable;
import io.ehdev.account.db.tables.SsUserconnectionTable;
import io.ehdev.account.db.tables.TargetAccessRuleTable;
import io.ehdev.account.db.tables.TargetTable;
import io.ehdev.account.db.tables.UserDetailsTable;
import io.ehdev.account.db.tables.UserTokensTable;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code>account_manager</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX;
    public static final Index FLYWAY_SCHEMA_HISTORY_PRIMARY = Indexes0.FLYWAY_SCHEMA_HISTORY_PRIMARY;
    public static final Index RULE_GRANT_GRANT_TO_USER = Indexes0.RULE_GRANT_GRANT_TO_USER;
    public static final Index RULE_GRANT_PRIMARY = Indexes0.RULE_GRANT_PRIMARY;
    public static final Index RULE_GRANT_RULE_ID = Indexes0.RULE_GRANT_RULE_ID;
    public static final Index SS_USERCONNECTION_PRIMARY = Indexes0.SS_USERCONNECTION_PRIMARY;
    public static final Index SS_USERCONNECTION_USERCONNECTIONRANK = Indexes0.SS_USERCONNECTION_USERCONNECTIONRANK;
    public static final Index TARGET_PRIMARY = Indexes0.TARGET_PRIMARY;
    public static final Index TARGET_TARGET_NAME = Indexes0.TARGET_TARGET_NAME;
    public static final Index TARGET_ACCESS_RULE_PRIMARY = Indexes0.TARGET_ACCESS_RULE_PRIMARY;
    public static final Index TARGET_ACCESS_RULE_TARGET_ID = Indexes0.TARGET_ACCESS_RULE_TARGET_ID;
    public static final Index USER_DETAILS_EMAIL = Indexes0.USER_DETAILS_EMAIL;
    public static final Index USER_DETAILS_PRIMARY = Indexes0.USER_DETAILS_PRIMARY;
    public static final Index USER_DETAILS_USER_REF = Indexes0.USER_DETAILS_USER_REF;
    public static final Index USER_TOKENS_PRIMARY = Indexes0.USER_TOKENS_PRIMARY;
    public static final Index USER_TOKENS_PUBLIC_USER_TOKEN = Indexes0.USER_TOKENS_PUBLIC_USER_TOKEN;
    public static final Index USER_TOKENS_USER_ID = Indexes0.USER_TOKENS_USER_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
        public static Index FLYWAY_SCHEMA_HISTORY_PRIMARY = Internal.createIndex("PRIMARY", FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
        public static Index RULE_GRANT_GRANT_TO_USER = Internal.createIndex("grant_to_user", RuleGrantTable.RULE_GRANT, new OrderField[] { RuleGrantTable.RULE_GRANT.USER_ID }, false);
        public static Index RULE_GRANT_PRIMARY = Internal.createIndex("PRIMARY", RuleGrantTable.RULE_GRANT, new OrderField[] { RuleGrantTable.RULE_GRANT.GRANT_ID }, true);
        public static Index RULE_GRANT_RULE_ID = Internal.createIndex("rule_id", RuleGrantTable.RULE_GRANT, new OrderField[] { RuleGrantTable.RULE_GRANT.RULE_ID, RuleGrantTable.RULE_GRANT.USER_ID }, true);
        public static Index SS_USERCONNECTION_PRIMARY = Internal.createIndex("PRIMARY", SsUserconnectionTable.SS_USERCONNECTION, new OrderField[] { SsUserconnectionTable.SS_USERCONNECTION.USERID, SsUserconnectionTable.SS_USERCONNECTION.PROVIDERID, SsUserconnectionTable.SS_USERCONNECTION.PROVIDERUSERID }, true);
        public static Index SS_USERCONNECTION_USERCONNECTIONRANK = Internal.createIndex("UserConnectionRank", SsUserconnectionTable.SS_USERCONNECTION, new OrderField[] { SsUserconnectionTable.SS_USERCONNECTION.USERID, SsUserconnectionTable.SS_USERCONNECTION.PROVIDERID, SsUserconnectionTable.SS_USERCONNECTION.RANK }, true);
        public static Index TARGET_PRIMARY = Internal.createIndex("PRIMARY", TargetTable.TARGET, new OrderField[] { TargetTable.TARGET.TARGET_ID }, true);
        public static Index TARGET_TARGET_NAME = Internal.createIndex("target_name", TargetTable.TARGET, new OrderField[] { TargetTable.TARGET.TARGET_NAME }, true);
        public static Index TARGET_ACCESS_RULE_PRIMARY = Internal.createIndex("PRIMARY", TargetAccessRuleTable.TARGET_ACCESS_RULE, new OrderField[] { TargetAccessRuleTable.TARGET_ACCESS_RULE.RULE_ID }, true);
        public static Index TARGET_ACCESS_RULE_TARGET_ID = Internal.createIndex("target_id", TargetAccessRuleTable.TARGET_ACCESS_RULE, new OrderField[] { TargetAccessRuleTable.TARGET_ACCESS_RULE.TARGET_ID, TargetAccessRuleTable.TARGET_ACCESS_RULE.RESOURCE_NAME, TargetAccessRuleTable.TARGET_ACCESS_RULE.ACTION_NAME }, true);
        public static Index USER_DETAILS_EMAIL = Internal.createIndex("email", UserDetailsTable.USER_DETAILS, new OrderField[] { UserDetailsTable.USER_DETAILS.EMAIL }, true);
        public static Index USER_DETAILS_PRIMARY = Internal.createIndex("PRIMARY", UserDetailsTable.USER_DETAILS, new OrderField[] { UserDetailsTable.USER_DETAILS.USER_ID }, true);
        public static Index USER_DETAILS_USER_REF = Internal.createIndex("user_ref", UserDetailsTable.USER_DETAILS, new OrderField[] { UserDetailsTable.USER_DETAILS.USER_REF }, true);
        public static Index USER_TOKENS_PRIMARY = Internal.createIndex("PRIMARY", UserTokensTable.USER_TOKENS, new OrderField[] { UserTokensTable.USER_TOKENS.USER_TOKEN_ID }, true);
        public static Index USER_TOKENS_PUBLIC_USER_TOKEN = Internal.createIndex("public_user_token", UserTokensTable.USER_TOKENS, new OrderField[] { UserTokensTable.USER_TOKENS.PUBLIC_USER_TOKEN }, true);
        public static Index USER_TOKENS_USER_ID = Internal.createIndex("user_id", UserTokensTable.USER_TOKENS, new OrderField[] { UserTokensTable.USER_TOKENS.USER_ID }, false);
    }
}
