/*
 * This file is generated by jOOQ.
 */
package io.ehdev.account.db;


import io.ehdev.account.db.tables.FlywaySchemaHistoryTable;
import io.ehdev.account.db.tables.RuleGrantTable;
import io.ehdev.account.db.tables.SsUserconnectionTable;
import io.ehdev.account.db.tables.TargetAccessRuleTable;
import io.ehdev.account.db.tables.TargetTable;
import io.ehdev.account.db.tables.UserDetailsTable;
import io.ehdev.account.db.tables.UserTokensTable;
import io.ehdev.account.db.tables.records.FlywaySchemaHistoryRecord;
import io.ehdev.account.db.tables.records.RuleGrantRecord;
import io.ehdev.account.db.tables.records.SsUserconnectionRecord;
import io.ehdev.account.db.tables.records.TargetAccessRuleRecord;
import io.ehdev.account.db.tables.records.TargetRecord;
import io.ehdev.account.db.tables.records.UserDetailsRecord;
import io.ehdev.account.db.tables.records.UserTokensRecord;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>account_manager</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<RuleGrantRecord, Long> IDENTITY_RULE_GRANT = Identities0.IDENTITY_RULE_GRANT;
    public static final Identity<TargetRecord, Long> IDENTITY_TARGET = Identities0.IDENTITY_TARGET;
    public static final Identity<TargetAccessRuleRecord, Long> IDENTITY_TARGET_ACCESS_RULE = Identities0.IDENTITY_TARGET_ACCESS_RULE;
    public static final Identity<UserDetailsRecord, Long> IDENTITY_USER_DETAILS = Identities0.IDENTITY_USER_DETAILS;
    public static final Identity<UserTokensRecord, Long> IDENTITY_USER_TOKENS = Identities0.IDENTITY_USER_TOKENS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = UniqueKeys0.KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY;
    public static final UniqueKey<RuleGrantRecord> KEY_RULE_GRANT_PRIMARY = UniqueKeys0.KEY_RULE_GRANT_PRIMARY;
    public static final UniqueKey<RuleGrantRecord> KEY_RULE_GRANT_RULE_ID = UniqueKeys0.KEY_RULE_GRANT_RULE_ID;
    public static final UniqueKey<SsUserconnectionRecord> KEY_SS_USERCONNECTION_PRIMARY = UniqueKeys0.KEY_SS_USERCONNECTION_PRIMARY;
    public static final UniqueKey<SsUserconnectionRecord> KEY_SS_USERCONNECTION_USERCONNECTIONRANK = UniqueKeys0.KEY_SS_USERCONNECTION_USERCONNECTIONRANK;
    public static final UniqueKey<TargetRecord> KEY_TARGET_PRIMARY = UniqueKeys0.KEY_TARGET_PRIMARY;
    public static final UniqueKey<TargetRecord> KEY_TARGET_TARGET_NAME = UniqueKeys0.KEY_TARGET_TARGET_NAME;
    public static final UniqueKey<TargetAccessRuleRecord> KEY_TARGET_ACCESS_RULE_PRIMARY = UniqueKeys0.KEY_TARGET_ACCESS_RULE_PRIMARY;
    public static final UniqueKey<TargetAccessRuleRecord> KEY_TARGET_ACCESS_RULE_TARGET_ID = UniqueKeys0.KEY_TARGET_ACCESS_RULE_TARGET_ID;
    public static final UniqueKey<UserDetailsRecord> KEY_USER_DETAILS_PRIMARY = UniqueKeys0.KEY_USER_DETAILS_PRIMARY;
    public static final UniqueKey<UserDetailsRecord> KEY_USER_DETAILS_USER_REF = UniqueKeys0.KEY_USER_DETAILS_USER_REF;
    public static final UniqueKey<UserDetailsRecord> KEY_USER_DETAILS_EMAIL = UniqueKeys0.KEY_USER_DETAILS_EMAIL;
    public static final UniqueKey<UserTokensRecord> KEY_USER_TOKENS_PRIMARY = UniqueKeys0.KEY_USER_TOKENS_PRIMARY;
    public static final UniqueKey<UserTokensRecord> KEY_USER_TOKENS_PUBLIC_USER_TOKEN = UniqueKeys0.KEY_USER_TOKENS_PUBLIC_USER_TOKEN;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<RuleGrantRecord, TargetAccessRuleRecord> GRANT_TO_RULE = ForeignKeys0.GRANT_TO_RULE;
    public static final ForeignKey<RuleGrantRecord, UserDetailsRecord> GRANT_TO_USER = ForeignKeys0.GRANT_TO_USER;
    public static final ForeignKey<TargetAccessRuleRecord, TargetRecord> RULE_TO_TARGET = ForeignKeys0.RULE_TO_TARGET;
    public static final ForeignKey<UserTokensRecord, UserDetailsRecord> USER_TOKENS_IBFK_1 = ForeignKeys0.USER_TOKENS_IBFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<RuleGrantRecord, Long> IDENTITY_RULE_GRANT = Internal.createIdentity(RuleGrantTable.RULE_GRANT, RuleGrantTable.RULE_GRANT.GRANT_ID);
        public static Identity<TargetRecord, Long> IDENTITY_TARGET = Internal.createIdentity(TargetTable.TARGET, TargetTable.TARGET.TARGET_ID);
        public static Identity<TargetAccessRuleRecord, Long> IDENTITY_TARGET_ACCESS_RULE = Internal.createIdentity(TargetAccessRuleTable.TARGET_ACCESS_RULE, TargetAccessRuleTable.TARGET_ACCESS_RULE.RULE_ID);
        public static Identity<UserDetailsRecord, Long> IDENTITY_USER_DETAILS = Internal.createIdentity(UserDetailsTable.USER_DETAILS, UserDetailsTable.USER_DETAILS.USER_ID);
        public static Identity<UserTokensRecord, Long> IDENTITY_USER_TOKENS = Internal.createIdentity(UserTokensTable.USER_TOKENS, UserTokensTable.USER_TOKENS.USER_TOKEN_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = Internal.createUniqueKey(FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY, "KEY_flyway_schema_history_PRIMARY", FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK);
        public static final UniqueKey<RuleGrantRecord> KEY_RULE_GRANT_PRIMARY = Internal.createUniqueKey(RuleGrantTable.RULE_GRANT, "KEY_rule_grant_PRIMARY", RuleGrantTable.RULE_GRANT.GRANT_ID);
        public static final UniqueKey<RuleGrantRecord> KEY_RULE_GRANT_RULE_ID = Internal.createUniqueKey(RuleGrantTable.RULE_GRANT, "KEY_rule_grant_rule_id", RuleGrantTable.RULE_GRANT.RULE_ID, RuleGrantTable.RULE_GRANT.USER_ID);
        public static final UniqueKey<SsUserconnectionRecord> KEY_SS_USERCONNECTION_PRIMARY = Internal.createUniqueKey(SsUserconnectionTable.SS_USERCONNECTION, "KEY_ss_UserConnection_PRIMARY", SsUserconnectionTable.SS_USERCONNECTION.USERID, SsUserconnectionTable.SS_USERCONNECTION.PROVIDERID, SsUserconnectionTable.SS_USERCONNECTION.PROVIDERUSERID);
        public static final UniqueKey<SsUserconnectionRecord> KEY_SS_USERCONNECTION_USERCONNECTIONRANK = Internal.createUniqueKey(SsUserconnectionTable.SS_USERCONNECTION, "KEY_ss_UserConnection_UserConnectionRank", SsUserconnectionTable.SS_USERCONNECTION.USERID, SsUserconnectionTable.SS_USERCONNECTION.PROVIDERID, SsUserconnectionTable.SS_USERCONNECTION.RANK);
        public static final UniqueKey<TargetRecord> KEY_TARGET_PRIMARY = Internal.createUniqueKey(TargetTable.TARGET, "KEY_target_PRIMARY", TargetTable.TARGET.TARGET_ID);
        public static final UniqueKey<TargetRecord> KEY_TARGET_TARGET_NAME = Internal.createUniqueKey(TargetTable.TARGET, "KEY_target_target_name", TargetTable.TARGET.TARGET_NAME);
        public static final UniqueKey<TargetAccessRuleRecord> KEY_TARGET_ACCESS_RULE_PRIMARY = Internal.createUniqueKey(TargetAccessRuleTable.TARGET_ACCESS_RULE, "KEY_target_access_rule_PRIMARY", TargetAccessRuleTable.TARGET_ACCESS_RULE.RULE_ID);
        public static final UniqueKey<TargetAccessRuleRecord> KEY_TARGET_ACCESS_RULE_TARGET_ID = Internal.createUniqueKey(TargetAccessRuleTable.TARGET_ACCESS_RULE, "KEY_target_access_rule_target_id", TargetAccessRuleTable.TARGET_ACCESS_RULE.TARGET_ID, TargetAccessRuleTable.TARGET_ACCESS_RULE.RESOURCE_NAME, TargetAccessRuleTable.TARGET_ACCESS_RULE.ACTION_NAME);
        public static final UniqueKey<UserDetailsRecord> KEY_USER_DETAILS_PRIMARY = Internal.createUniqueKey(UserDetailsTable.USER_DETAILS, "KEY_user_details_PRIMARY", UserDetailsTable.USER_DETAILS.USER_ID);
        public static final UniqueKey<UserDetailsRecord> KEY_USER_DETAILS_USER_REF = Internal.createUniqueKey(UserDetailsTable.USER_DETAILS, "KEY_user_details_user_ref", UserDetailsTable.USER_DETAILS.USER_REF);
        public static final UniqueKey<UserDetailsRecord> KEY_USER_DETAILS_EMAIL = Internal.createUniqueKey(UserDetailsTable.USER_DETAILS, "KEY_user_details_email", UserDetailsTable.USER_DETAILS.EMAIL);
        public static final UniqueKey<UserTokensRecord> KEY_USER_TOKENS_PRIMARY = Internal.createUniqueKey(UserTokensTable.USER_TOKENS, "KEY_user_tokens_PRIMARY", UserTokensTable.USER_TOKENS.USER_TOKEN_ID);
        public static final UniqueKey<UserTokensRecord> KEY_USER_TOKENS_PUBLIC_USER_TOKEN = Internal.createUniqueKey(UserTokensTable.USER_TOKENS, "KEY_user_tokens_public_user_token", UserTokensTable.USER_TOKENS.PUBLIC_USER_TOKEN);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<RuleGrantRecord, TargetAccessRuleRecord> GRANT_TO_RULE = Internal.createForeignKey(io.ehdev.account.db.Keys.KEY_TARGET_ACCESS_RULE_PRIMARY, RuleGrantTable.RULE_GRANT, "grant_to_rule", RuleGrantTable.RULE_GRANT.RULE_ID);
        public static final ForeignKey<RuleGrantRecord, UserDetailsRecord> GRANT_TO_USER = Internal.createForeignKey(io.ehdev.account.db.Keys.KEY_USER_DETAILS_PRIMARY, RuleGrantTable.RULE_GRANT, "grant_to_user", RuleGrantTable.RULE_GRANT.USER_ID);
        public static final ForeignKey<TargetAccessRuleRecord, TargetRecord> RULE_TO_TARGET = Internal.createForeignKey(io.ehdev.account.db.Keys.KEY_TARGET_PRIMARY, TargetAccessRuleTable.TARGET_ACCESS_RULE, "rule_to_target", TargetAccessRuleTable.TARGET_ACCESS_RULE.TARGET_ID);
        public static final ForeignKey<UserTokensRecord, UserDetailsRecord> USER_TOKENS_IBFK_1 = Internal.createForeignKey(io.ehdev.account.db.Keys.KEY_USER_DETAILS_PRIMARY, UserTokensTable.USER_TOKENS, "user_tokens_ibfk_1", UserTokensTable.USER_TOKENS.USER_ID);
    }
}
