/*
 * This file is generated by jOOQ.
 */
package io.ehdev.account.db.tables.records;


import io.ehdev.account.db.tables.RuleGrantTable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "rule_grant", schema = "account_manager", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"rule_id", "user_id"})
}, indexes = {
    @Index(name = "grant_to_user", columnList = "user_id ASC"),
    @Index(name = "PRIMARY", unique = true, columnList = "grant_id ASC"),
    @Index(name = "rule_id", unique = true, columnList = "rule_id ASC, user_id ASC")
})
public class RuleGrantRecord extends UpdatableRecordImpl<RuleGrantRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = -1143688651;

    /**
     * Setter for <code>account_manager.rule_grant.grant_id</code>.
     */
    public void setGrantId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>account_manager.rule_grant.grant_id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "grant_id", unique = true, nullable = false, precision = 19)
    public Long getGrantId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>account_manager.rule_grant.rule_id</code>.
     */
    public void setRuleId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>account_manager.rule_grant.rule_id</code>.
     */
    @Column(name = "rule_id", nullable = false, precision = 19)
    @NotNull
    public Long getRuleId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>account_manager.rule_grant.user_id</code>.
     */
    public void setUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>account_manager.rule_grant.user_id</code>.
     */
    @Column(name = "user_id", nullable = false, precision = 19)
    @NotNull
    public Long getUserId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return RuleGrantTable.RULE_GRANT.GRANT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return RuleGrantTable.RULE_GRANT.RULE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return RuleGrantTable.RULE_GRANT.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getGrantId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getRuleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getGrantId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getRuleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RuleGrantRecord value1(Long value) {
        setGrantId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RuleGrantRecord value2(Long value) {
        setRuleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RuleGrantRecord value3(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RuleGrantRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RuleGrantRecord
     */
    public RuleGrantRecord() {
        super(RuleGrantTable.RULE_GRANT);
    }

    /**
     * Create a detached, initialised RuleGrantRecord
     */
    public RuleGrantRecord(Long grantId, Long ruleId, Long userId) {
        super(RuleGrantTable.RULE_GRANT);

        set(0, grantId);
        set(1, ruleId);
        set(2, userId);
    }
}
