/*
 * This file is generated by jOOQ.
 */
package io.ehdev.account.db.tables.records;


import io.ehdev.account.db.tables.TargetAccessRuleTable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "target_access_rule", schema = "account_manager", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"target_id", "resource_name", "action_name"})
}, indexes = {
    @Index(name = "PRIMARY", unique = true, columnList = "rule_id ASC"),
    @Index(name = "target_id", unique = true, columnList = "target_id ASC, resource_name ASC, action_name ASC")
})
public class TargetAccessRuleRecord extends UpdatableRecordImpl<TargetAccessRuleRecord> implements Record4<Long, Long, String, String> {

    private static final long serialVersionUID = 305464813;

    /**
     * Setter for <code>account_manager.target_access_rule.rule_id</code>.
     */
    public void setRuleId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>account_manager.target_access_rule.rule_id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "rule_id", unique = true, nullable = false, precision = 19)
    public Long getRuleId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>account_manager.target_access_rule.target_id</code>.
     */
    public void setTargetId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>account_manager.target_access_rule.target_id</code>.
     */
    @Column(name = "target_id", nullable = false, precision = 19)
    @NotNull
    public Long getTargetId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>account_manager.target_access_rule.resource_name</code>.
     */
    public void setResourceName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>account_manager.target_access_rule.resource_name</code>.
     */
    @Column(name = "resource_name", nullable = false, length = 128)
    @NotNull
    @Size(max = 128)
    public String getResourceName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>account_manager.target_access_rule.action_name</code>.
     */
    public void setActionName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>account_manager.target_access_rule.action_name</code>.
     */
    @Column(name = "action_name", nullable = false, length = 128)
    @NotNull
    @Size(max = 128)
    public String getActionName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TargetAccessRuleTable.TARGET_ACCESS_RULE.RULE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return TargetAccessRuleTable.TARGET_ACCESS_RULE.TARGET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TargetAccessRuleTable.TARGET_ACCESS_RULE.RESOURCE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TargetAccessRuleTable.TARGET_ACCESS_RULE.ACTION_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getRuleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getTargetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getResourceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getActionName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getRuleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getTargetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getResourceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getActionName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TargetAccessRuleRecord value1(Long value) {
        setRuleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TargetAccessRuleRecord value2(Long value) {
        setTargetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TargetAccessRuleRecord value3(String value) {
        setResourceName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TargetAccessRuleRecord value4(String value) {
        setActionName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TargetAccessRuleRecord values(Long value1, Long value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TargetAccessRuleRecord
     */
    public TargetAccessRuleRecord() {
        super(TargetAccessRuleTable.TARGET_ACCESS_RULE);
    }

    /**
     * Create a detached, initialised TargetAccessRuleRecord
     */
    public TargetAccessRuleRecord(Long ruleId, Long targetId, String resourceName, String actionName) {
        super(TargetAccessRuleTable.TARGET_ACCESS_RULE);

        set(0, ruleId);
        set(1, targetId);
        set(2, resourceName);
        set(3, actionName);
    }
}
