/*
 * This file is generated by jOOQ.
 */
package io.ehdev.account.db.tables;


import io.ehdev.account.db.AccountManager;
import io.ehdev.account.db.Indexes;
import io.ehdev.account.db.Keys;
import io.ehdev.account.db.converter.TimestampConverter;
import io.ehdev.account.db.tables.records.UserTokensRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.time.Instant;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTokensTable extends TableImpl<UserTokensRecord> {

    private static final long serialVersionUID = 739981629;

    /**
     * The reference instance of <code>account_manager.user_tokens</code>
     */
    public static final UserTokensTable USER_TOKENS = new UserTokensTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserTokensRecord> getRecordType() {
        return UserTokensRecord.class;
    }

    /**
     * The column <code>account_manager.user_tokens.user_token_id</code>.
     */
    public final TableField<UserTokensRecord, Long> USER_TOKEN_ID = createField("user_token_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>account_manager.user_tokens.public_user_token</code>.
     */
    public final TableField<UserTokensRecord, String> PUBLIC_USER_TOKEN = createField("public_user_token", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>account_manager.user_tokens.created_at</code>.
     */
    public final TableField<UserTokensRecord, Instant> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "", new TimestampConverter());

    /**
     * The column <code>account_manager.user_tokens.expires_at</code>.
     */
    public final TableField<UserTokensRecord, Instant> EXPIRES_AT = createField("expires_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP(6)", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "", new TimestampConverter());

    /**
     * The column <code>account_manager.user_tokens.valid</code>.
     */
    public final TableField<UserTokensRecord, Boolean> VALID = createField("valid", org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>account_manager.user_tokens.user_id</code>.
     */
    public final TableField<UserTokensRecord, Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>account_manager.user_tokens</code> table reference
     */
    public UserTokensTable() {
        this(DSL.name("user_tokens"), null);
    }

    /**
     * Create an aliased <code>account_manager.user_tokens</code> table reference
     */
    public UserTokensTable(String alias) {
        this(DSL.name(alias), USER_TOKENS);
    }

    /**
     * Create an aliased <code>account_manager.user_tokens</code> table reference
     */
    public UserTokensTable(Name alias) {
        this(alias, USER_TOKENS);
    }

    private UserTokensTable(Name alias, Table<UserTokensRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserTokensTable(Name alias, Table<UserTokensRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> UserTokensTable(Table<O> child, ForeignKey<O, UserTokensRecord> key) {
        super(child, key, USER_TOKENS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return AccountManager.ACCOUNT_MANAGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.USER_TOKENS_PRIMARY, Indexes.USER_TOKENS_PUBLIC_USER_TOKEN, Indexes.USER_TOKENS_USER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UserTokensRecord, Long> getIdentity() {
        return Keys.IDENTITY_USER_TOKENS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserTokensRecord> getPrimaryKey() {
        return Keys.KEY_USER_TOKENS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserTokensRecord>> getKeys() {
        return Arrays.<UniqueKey<UserTokensRecord>>asList(Keys.KEY_USER_TOKENS_PRIMARY, Keys.KEY_USER_TOKENS_PUBLIC_USER_TOKEN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UserTokensRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserTokensRecord, ?>>asList(Keys.USER_TOKENS_IBFK_1);
    }

    public UserDetailsTable userDetails() {
        return new UserDetailsTable(this, Keys.USER_TOKENS_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTokensTable as(String alias) {
        return new UserTokensTable(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTokensTable as(Name alias) {
        return new UserTokensTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTokensTable rename(String name) {
        return new UserTokensTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTokensTable rename(Name name) {
        return new UserTokensTable(name, null);
    }
}
